hostapp-update-hooks: Rework for Orin Nano
so that it:
- performs the UEFI variables set in the current running hostOS,
  because the OS now bindmounts /sys/firmware/efi/efivars in the HUP
  container
- copies the Jetpack 5 Orin Nano device-tree under the Jetpack 6 name,
  so in case of an altboot rollback, the JP6 bootloader, ran by the
  fallback boot slot firmware can load it and boot the JP5 kernel.

Signed-off-by: Alexandru Costache <alexandru@balena.io>

diff --git a/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-orin-nano-devkit-nvme b/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-orin-nano-devkit-nvme
--- a/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-orin-nano-devkit-nvme
+++ b/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-orin-nano-devkit-nvme
@@ -9,6 +9,20 @@ set -o errexit
 . /usr/libexec/os-helpers-fs
 . /usr/sbin/balena-config-vars
 
+efivars_dir="/sys/firmware/efi/efivars/"
+# See https://github.com/OE4T/meta-tegra/blob/master/recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
+platform_spec_efivar="${efivars_dir}TegraPlatformSpec-781e084c-a330-417c-b678-38e696380cb9"
+platform_compat_spec_efivar="${efivars_dir}TegraPlatformCompatSpec-781e084c-a330-417c-b678-38e696380cb9"
+os_indications_efivar="${efivars_dir}OsIndications-8be4df61-93ca-11d2-aa0d-00e098032b8c"
+tmp_file="/tmp/platformspecfile.bin"
+active_sysroot="/mnt/sysroot/active/current/boot/"
+jp5_default_dtb_name="tegra234-p3767-0003-p3768-0000-a0.dtb"
+jp6_default_dtb_name="tegra234-p3768-0000+p3767-0005-nv.dtb"
+
+device_type="jetson-orin-nano-devkit"
+
+source /usr/bin/uefi_common.func
+
 DURING_UPDATE=${DURING_UPDATE:-0}
 bootloader_device="/dev/mtdblock0"
 internal_storage="/dev/nvme0n1"
@@ -16,10 +30,59 @@ use_capsule=1
 
 bootloader_blob="/opt/tegra-binaries/TEGRA_BL_Orin_Nano.Cap.gz"
 
+boardspec=$(tegra-boardspec 2>/dev/null)
+TegraPlatformSpec="${boardspec}-${device_type}-"
+compatspec=$(echo "$boardspec" | gen_compat_spec)
+TegraPlatformCompatSpec="${compatspec}-${device_type}-"
+
 info_log()
 {
     echo "[INFO] $@"
 }
+
+write_jetson_update_efivars() {
+    info "Writing of jetson efivars triggered from old OS hook"
+    if [ -d $efivars_dir ]; then
+        # If the file already exists, writing to it will fail
+        # causing the entire hook to fail
+        if [ ! -e ${platform_spec_efivar} ]; then
+            printf "\x07\x00\x00\x00" > ${tmp_file}
+            printf "%s" "${TegraPlatformSpec}" >> ${tmp_file}
+            dd if=${tmp_file} of=${platform_spec_efivar}
+            info "PlatformSpec variable created"
+        else
+            info "PlatformSpec variable already exists"
+        fi
+
+        if [ ! -e ${platform_compat_spec_efivar} ]; then
+            printf "\x07\x00\x00\x00" > ${tmp_file}
+            printf "%s" "${TegraPlatformCompatSpec}" >> ${tmp_file}
+            dd if=${tmp_file} of=${platform_compat_spec_efivar}
+            info "PlatformCompatSpec variable created"
+        else
+            info "PlatformCompatSpec variable already exists"
+        fi
+
+        printf "%b" '\x07\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00' > ${tmp_file}
+        dd if=${tmp_file} of=${os_indications_efivar}
+        info "OsIndications variable written"
+    else
+        info "sysfs not accessible!"
+        return 1
+    fi
+
+    return 0
+}
+
+copy_jp5_dtb() {
+    if [ -f ${active_sysroot}${jp5_default_dtb_name} ]; then
+        cp ${active_sysroot}${jp5_default_dtb_name} ${active_sysroot}${jp6_default_dtb_name} || true
+       info "Copied old dtb under new name"
+    else
+        info "Jetpack 5 default device-tree not found"
+    fi
+}
+
 
 # While the UEFI firmware accepts loading the uefi bootloader
 # from any partition, it doesn't do the same for
@@ -64,17 +127,11 @@ info "Bootloader blob is $bootloader_blob"
 
 do_capsule_update() {
     # Unzip capsule to the boot partition
+    info "Will extract UEFI Capsule..."
     mkdir -p /mnt/boot/EFI/UpdateCapsule/
     gunzip -k -c ${bootloader_blob} | dd of=/mnt/boot/EFI/UpdateCapsule/TEGRA_BL.Cap
     sync
-
-    if [ $(ls -l ${efivars_dir}OsIndications* | wc -l) -gt 0 ]; then
-        info "Once a release that bindmounts sysfs is available in production, the efi vars can be updated from here instead of the after hook"
-    else
-        # Once the above condition is met, we could drop the after hook and use the legacy update mode if the base release is older
-        # than the one with sysfs bindmount in hostapp-update
-        info "Sysfs directory exists, but is not bindmounted. After hook will write the efi variables from the old OS"
-    fi
+    info "Extracted UEFI Capsule."
 }
 
 info "Pre-update A/B slots info:"
@@ -84,3 +141,38 @@ info "=========================="
 
 do_capsule_update
 check_and_update_esp_flags
+
+
+# Save next active boot slot
+# so it can be processed by the UEFI bootloader
+process_bootslot_file() {
+    if [ "$DURING_UPDATE" = "1" ]; then
+        bootslotchar=$(nvbootctrl dump-slots-info | grep Active | awk '{print $4}')
+
+        echo "bootslotchar is $bootslotchar"
+
+        if [ "$bootslotchar" = "A" ]; then
+            # next slot will be B
+            nextbootslot="1";
+        else
+            # next slot will be A
+            nextbootslot="0";
+        fi
+
+        echo "Next boot slot is ${nextbootslot}. Will be written to bootslot.env"
+        echo "bootslot=${nextbootslot}" > /mnt/boot/bootslot.env
+        cat /mnt/boot/bootslot.env
+    else
+        echo "During rollback, will remove bootslot.env"
+        rm -rf /mnt/boot/bootslot.env || true
+    fi
+}
+
+process_bootslot_file
+copy_jp5_dtb
+
+if [ $(ls -l ${efivars_dir}OsIndications* | wc -l) -gt 0 ]; then
+    write_jetson_update_efivars
+else
+    echo "efivars directory is is empty"
+fi
