hostapp-update-hooks: Rework to use legacy update if starting from L4T 35.1
Signed-off-by: Alexandru Costache <alexandru@balena.io>

diff --git a/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit b/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit
--- a/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit
+++ b/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit
@@ -12,15 +12,18 @@ set -o errexit
 DURING_UPDATE=${DURING_UPDATE:-0}
 declare -a UPDATED_PARTITIONS=()
 efivars_dir="/sys/firmware/efi/efivars/"
+# See https://github.com/OE4T/meta-tegra/blob/master/recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
 platform_spec_efivar="${efivars_dir}TegraPlatformSpec-781e084c-a330-417c-b678-38e696380cb9"
 platform_compat_spec_efivar="${efivars_dir}TegraPlatformCompatSpec-781e084c-a330-417c-b678-38e696380cb9"
 os_indications_efivar="${efivars_dir}OsIndications-8be4df61-93ca-11d2-aa0d-00e098032b8c"
 tmp_file="/tmp/platformspecfile.bin"
 bootloader_device="/dev/mtdblock0"
+use_capsule=1
+
 if cat /proc/device-tree/nvidia,dtsfilename | grep -q "p3701-0000" ; then 
     bootloader_blob="/opt/tegra-binaries/TEGRA_BL_3701_000.Cap.gz"
 else
-   bootloader_blob="/opt/tegra-binaries/TEGRA_BL_3701_300.Cap.gz"
+    bootloader_blob="/opt/tegra-binaries/TEGRA_BL_3701_300.Cap.gz"
 fi
 
 info_log()
@@ -35,6 +38,7 @@ check_disable_xudc()
     if [ -e $extlinuxfile ]; then
        if grep -q "l4tver=35.1.0" "${extlinuxfile}"; then
             info_log "Old root is running L4T 35.1.0, will disable tegra-xudc from the device-trees"
+            use_capsule=0
             for dtbfile in `find /mnt/sysroot/active/ -name "*.dtb" -type f`; do
                 info_log "Disabling tegra-xudc in $dtbfile ...";
                 fdtput -t s $dtbfile /xudc status disabled
@@ -74,6 +78,7 @@ check_and_update_esp_flags() {
     if [ "$esp_type" = "$esp_part_type" ]; then
         info_log "esp partition has esp flag, will be cleared"
         sfdisk --part-type /dev/mmcblk0 $esp_index $data_type
+        sync
     else
         info_log "no type change needed on esp partition"
     fi
@@ -81,6 +86,7 @@ check_and_update_esp_flags() {
     if [ "$resin_boot_part_type" != "$esp_type" ]; then
         info_log "resin-boot partition does not have esp type, must be added"
         sfdisk --part-type /dev/mmcblk0 $resin_boot_index $esp_type
+        sync
     else
         info_log "no type change needed on resin-boot partition"
     fi
@@ -91,24 +97,51 @@ check_and_update_esp_flags
 
 info "Bootloader blob is $bootloader_blob"
 
-# Unzip capsule to the boot partition
-mkdir -p /mnt/boot/EFI/UpdateCapsule/
-zcat ${bootloader_blob} > /mnt/boot/EFI/UpdateCapsule/TEGRA_BL.Cap
-sync
+do_capsule_update() {
+    # Unzip capsule to the boot partition
+    mkdir -p /mnt/boot/EFI/UpdateCapsule/
+    zcat ${bootloader_blob} > /mnt/boot/EFI/UpdateCapsule/TEGRA_BL.Cap
+    sync
 
-# If the file already exists, writing to it will fail
-# causing the entire hook to fail
-if [ ! -e ${platform_spec_efivar} ]; then
-    printf "\x07\x00\x00\x00" > ${tmp_file}
-    printf "%s" "3701-500-0000-J.0-1-1-jetson-agx-orin-devkit-" >> ${tmp_file}
-    dd if=${tmp_file} of=${platform_spec_efivar}
+    # If the file already exists, writing to it will fail
+    # causing the entire hook to fail
+    if [ ! -e ${platform_spec_efivar} ]; then
+        printf "\x07\x00\x00\x00" > ${tmp_file}
+        printf "%s" "3701-500-0000-J.0-1-1-jetson-agx-orin-devkit-" >> ${tmp_file}
+        dd if=${tmp_file} of=${platform_spec_efivar}
+    fi
+
+    if [ ! -e ${platform_compat_spec_efivar} ]; then
+        printf "\x07\x00\x00\x00" > ${tmp_file}
+        printf "%s" "3701--0000--1--jetson-agx-orin-devkit-" >> ${tmp_file}
+        dd if=${tmp_file} of=${platform_compat_spec_efivar}
+    fi
+
+    printf "%b" '\x07\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00' > ${tmp_file}
+    dd if=${tmp_file} of=${os_indications_efivar}
+}
+
+do_legacy_update() {
+    bootloader_blob="/opt/tegra-binaries/boot0.img.gz"
+    existing_bootloader_md5sum=$(dd if=$bootloader_device bs=1M status=none | md5sum | awk '{print $1}')
+    update_bootloader_md5sum=$(md5sum $bootloader_blob | awk '{print $1}')
+
+    if [ ! "$existing_bootloader_md5sum" = "$update_bootloader_md5sum" ]; then
+        info_log "Will clear bootloader device before the update"
+        flash_erase /dev/mtd0 0 0 || true
+        info_log "Updating bootloader device"
+        zcat $bootloader_blob > $bootloader_device
+        info_log "Updated bootloader device"
+    else
+        info_log "No need to update bootloader device"
+    fi
+
+    # Sync internal memory
+    sync /dev/mtdblock0
+}
+
+if [ $use_capsule -eq 1 ]; then
+    do_capsule_update
+else
+    do_legacy_update
 fi
-
-if [ ! -e ${platform_compat_spec_efivar} ]; then
-    printf "\x07\x00\x00\x00" > ${tmp_file}
-    printf "%s" "3701--0000--1--jetson-agx-orin-devkit-" >> ${tmp_file}
-    dd if=${tmp_file} of=${platform_compat_spec_efivar}
-fi
-
-printf "%b" '\x07\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00' > ${tmp_file}
-dd if=${tmp_file} of=${os_indications_efivar}
