hostapp-update-hooks: Move uefi variable writing to the current OS hook
... for the AGX Orin and ensure there's no leftover capsule
in the boot partition, which could potentially cause rollbacks
to fail due to lack of space. In this commit we also extract the
UEFI capsule to the esp partition, because with recent BSP updates
it has become larger than what can fit into the boot partition.

Signed-off-by: Alexandru Costache <alexandru@balena.io>
Changelog-entry: hostapp-update-hooks: Move uefi variable writing to the current OS hook

diff --git a/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit b/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit
--- a/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit
+++ b/layers/meta-balena-jetson/recipes-support/hostapp-update-hooks/files/99-resin-bootfiles-agx-orin-devkit
@@ -5,20 +5,59 @@ set -o errexit
 # device tree with embedded cmdline
 # and updates the kernel, as well as
 # the rest of the bootloader binaries
-
 . /usr/libexec/os-helpers-fs
 . /usr/sbin/balena-config-vars
+source /usr/bin/uefi_common.func
 
 DURING_UPDATE=${DURING_UPDATE:-0}
+bootloader_blob="/opt/tegra-binaries/TEGRA_BL_3701.Cap.gz"
 bootloader_device="/dev/mtdblock0"
 internal_storage="/dev/mmcblk0"
 use_capsule=1
+efivars_dir="/sys/firmware/efi/efivars/"
+# See https://github.com/OE4T/meta-tegra/blob/master/recipes-bsp/tools/setup-nv-boot-control/setup-nv-boot-control.sh.in
+platform_spec_efivar="${efivars_dir}TegraPlatformSpec-781e084c-a330-417c-b678-38e696380cb9"
+platform_compat_spec_efivar="${efivars_dir}TegraPlatformCompatSpec-781e084c-a330-417c-b678-38e696380cb9"
+os_indications_efivar="${efivars_dir}OsIndications-8be4df61-93ca-11d2-aa0d-00e098032b8c"
+tmp_file="/tmp/platformspecfile.bin"
+device_type="jetson-agx-orin-devkit"
+boardspec=$(tegra-boardspec 2>/dev/null)
+TegraPlatformSpec="${boardspec}-${device_type}-"
+compatspec=$(echo "$boardspec" | gen_compat_spec)
+TegraPlatformCompatSpec="${compatspec}-${device_type}-"
 
-bootloader_blob="/opt/tegra-binaries/TEGRA_BL_3701.Cap.gz"
+write_jetson_update_efivars() {
+    info "Writing of jetson efivars triggered from old OS hook"
+    if [ -d $efivars_dir ]; then
+        # If the file already exists, writing to it will fail
+        # causing the entire hook to fail
+        if [ ! -e ${platform_spec_efivar} ]; then
+            printf "\x07\x00\x00\x00" > ${tmp_file}
+            printf "%s" "${TegraPlatformSpec}" >> ${tmp_file}
+            dd if=${tmp_file} of=${platform_spec_efivar}
+            info "PlatformSpec variable created"
+        else
+            info "PlatformSpec variable already exists"
+        fi
 
-info_log()
-{
-    echo "[INFO] $@"
+        if [ ! -e ${platform_compat_spec_efivar} ]; then
+            printf "\x07\x00\x00\x00" > ${tmp_file}
+            printf "%s" "${TegraPlatformCompatSpec}" >> ${tmp_file}
+            dd if=${tmp_file} of=${platform_compat_spec_efivar}
+            info "PlatformCompatSpec variable created"
+        else
+            info "PlatformCompatSpec variable already exists"
+        fi
+
+        printf "%b" '\x07\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00' > ${tmp_file}
+        dd if=${tmp_file} of=${os_indications_efivar}
+        info "OsIndications variable written"
+    else
+        fail "sysfs not accessible!"
+        return 1
+    fi
+
+    return 0
 }
 
 check_disable_xudc()
@@ -27,21 +66,22 @@ check_disable_xudc()
 
     if [ -e $extlinuxfile ]; then
        if grep -q "l4tver=35.1.0" "${extlinuxfile}"; then
-            info_log "Old root is running L4T 35.1.0, will disable tegra-xudc from the device-trees"
+            info "Old root is running L4T 35.1.0, will disable tegra-xudc from the device-trees"
             use_capsule=0
             for dtbfile in `find /mnt/sysroot/active/ -name "*.dtb" -type f`; do
-                info_log "Disabling tegra-xudc in $dtbfile ...";
+                info "Disabling tegra-xudc in $dtbfile ...";
                 fdtput -t s $dtbfile /xudc status disabled
                 fdtput -t s $dtbfile / nvidia,dtsfilename "tegra234-p3701-0000-p3737-0000_xudc_disabled.dts"
                 current_xudc_status=$(fdtget $dtbfile /xudc status)
-                info_log "$dtbfile now has xudc $current_xudc_status"
+                info "$dtbfile now has xudc $current_xudc_status"
             done
         else
-            info_log "extlinux file not found in old rootfs"
+            info "extlinux file not found in old rootfs"
         fi;
     fi;
 }
 
+# TODO: Reword comment
 # While the UEFI firmware accepts loading the uefi bootloader
 # from any partition, it doesn't do the same for
 # the update capsule, which needs to reside on a partition
@@ -56,7 +96,6 @@ check_disable_xudc()
 # from the boot partition, and instead will read the
 # capsule and perform the update.
 check_and_update_esp_flags() {
-    data_type="EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"
     esp_type="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
     esp_index="5"
     resin_boot_index="6"
@@ -64,20 +103,20 @@ check_and_update_esp_flags() {
     esp_part_type=$(sfdisk --part-type $internal_storage $esp_index)
     resin_boot_part_type=$(sfdisk --part-type $internal_storage $resin_boot_index)
 
-    if [ "$esp_type" = "$esp_part_type" ]; then
-        info_log "esp partition has esp flag, will be cleared"
-        sfdisk --part-type $internal_storage $esp_index $data_type
-        sync
+    if [ "$esp_type" != "$esp_part_type" ]; then
+        info "type change needed on esp partition"
+	sfdisk --part-type $internal_storage $esp_index $esp_type
+	sync
     else
-        info_log "no type change needed on esp partition"
+        info "ok - esp partition has esp flag"
     fi
 
     if [ "$resin_boot_part_type" != "$esp_type" ]; then
-        info_log "resin-boot partition does not have esp type, must be added"
+        info "resin-boot partition does not have esp type, must be added"
         sfdisk --part-type $internal_storage $resin_boot_index $esp_type
         sync
     else
-        info_log "no type change needed on resin-boot partition"
+        info "no type change needed on resin-boot partition"
     fi
 }
 
@@ -85,19 +124,42 @@ check_disable_xudc
 
 info "Bootloader blob is $bootloader_blob"
 
-do_capsule_update() {
-    # Unzip capsule to the boot partition
-    mkdir -p /mnt/boot/EFI/UpdateCapsule/
-    gunzip -k -c ${bootloader_blob} | dd of=/mnt/boot/EFI/UpdateCapsule/TEGRA_BL.Cap
-    sync
+# This allows for writing UEFI variables
+# in L4T 36.3, in the case where the hook
+# is triggered by the rollback-health script
+unload_spi_drivers() {
+spi_modules=("spi_tegra210_quad" "spi_tegra114")
 
-    if [ $(ls -l ${efivars_dir}OsIndications* | wc -l) -gt 0 ]; then
-        info "Once a release that bindmounts sysfs is available in production, the efi vars can be updated from here instead of the after hook"
-    else
-        # Once the above condition is met, we could drop the after hook and use the legacy update mode if the base release is older
-        # than the one with sysfs bindmount in hostapp-update
-        info "Sysfs directory exists, but is not bindmounted. After hook will write the efi variables from the old OS"
+for spi_module in "${spi_modules[@]}"
+do
+    if lsmod | grep -q $spi_module ; then
+        echo "Unloading $spi_module"
+        rmmod $spi_module
+
+        if [ $? -eq 0 ]; then
+            echo "Unloaded $spi_module"
+        fi
     fi
+done
+}
+
+unload_spi_drivers
+do_capsule_update() {
+    esp_dev=$(get_state_path_from_label "esp")
+    esp_tmp_dir="/tmp/esp/"
+    capsule_dir="/EFI/UpdateCapsule/"
+    /usr/sbin/mkfs.vfat ${esp_dev}
+    mkdir -p ${esp_tmp_dir}
+    mount ${esp_dev} ${esp_tmp_dir}
+    mkdir -p "${esp_tmp_dir}${capsule_dir}"
+    # Unzip capsule to the esp partition, because the uncompressed capsule size
+    # is too large for the boot partition
+    mkdir -p "${esp_tmp_dir}${capsule_dir}"
+    gunzip -k -c ${bootloader_blob} | dd of="${esp_tmp_dir}${capsule_dir}TEGRA_BL.Cap"
+    sync
+    umount $esp_dev
+    rm -rf $esp_tmp_dir || true
+    write_jetson_update_efivars
 }
 
 do_legacy_update() {
@@ -106,19 +168,18 @@ do_legacy_update() {
     update_bootloader_md5sum=$(md5sum $bootloader_blob | awk '{print $1}')
 
     if [ ! "$existing_bootloader_md5sum" = "$update_bootloader_md5sum" ]; then
-        info_log "Will clear bootloader device before the update"
+        info "Will clear bootloader device before the update"
         flash_erase /dev/mtd0 0 0 || true
-        info_log "Updating bootloader device"
+        info "Updating bootloader device"
         gunzip -k -c $bootloader_blob | dd of=$bootloader_device
-        info_log "Updated bootloader device"
+        info "Updated bootloader device"
     else
-        info_log "No need to update bootloader device"
+        info "No need to update bootloader device"
     fi
 
     # Sync internal memory
     sync ${bootloader_device}
 }
-
 
 info "Pre-update A/B slots info:"
 info "=========================="
